POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "linhthuy2",
    "password" : "tl020304",
    "c_password" : "tl020304"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "linhthuy",
    "password" : "tl020304"
}
###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU

{
    "title":"post no.4",
    "pdesc": "new post 4",
    "url": "facebook.com/linhthuy234",
    "status": "in work"
}
###
GET http://localhost:5000/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU

{
    "title":"post no.4",
    "pdesc": "new post 4",
    "url": "facebook.com/linhthuy234",
    "status": "in work"
}
###
PUT http://localhost:5000/api/posts/6411fc14ca6d762a3ac1fa67
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU

{
    "title":"post no.3",
    "pdesc": "new post 3",
    "url": "facebook.com/linhthuy123",
    "status": "in work"
}
###
DELETE  http://localhost:5000/api/posts/6411fd48ae6aaf604535c338
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU

{
    "title":"post no.4",
    "pdesc": "new post 4",
    "url": "facebook.com/linhthuy234",
    "status": "in work"
}
###
POST http://localhost:5000/api/comment/641338ef80788935bcf9a644
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU

{
    "content":"Linh is my mom",
    "status": "Feedback"
}
###
DELETE  http://localhost:5000/api/comment/641338ef80788935bcf9a644/64134161d0c702b6616c7cc7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU

{
    "content":"Linh is my pretty mom, and i love her so much",
    "status": "Feedback"
}
###
GET http://localhost:5000/api/posts/getallpost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExZjc5MDIxYjE4Y2Q0ZTAxNjVjM2YiLCJpYXQiOjE2Nzg5MDAyMTl9.w0J-nBfQRmQgWOtpIoe0saFkT3undZnC3pCRVM_g5hU