POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "huytgio147",
    "password" : "147852Huytgio"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "huytgio14",
    "password" : "147852Huytgio"
}